name: Build and push Docker image

on:
  push:
    branches:
      - master
      - next
      - "1.8"

jobs:
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: henrist/zerotier-one:${{ steps.extract_branch.outputs.branch }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
